### PR TITLE
ButtonMerchant scheme and target update to make Carthage installation work

### PR DESCRIPTION
**Pull request by AlinaChernenko**
Carthage installation doesn't work. Please check this open issue https://github.com/button/button-merchant-ios/issues/6.

I went ahead and changed ButtonMerchant scheme container and removed extra dependencies for ButtonMerchant target. Now Carthage and Pod work and all targets are building in the workspace.

Let me know if that makes sense or let's resolve this issue together.

### CODE REVIEW

**Comment by wessmith** [comment]
Hi @AlinaChernenko. Thanks for this! I'll make some time to review this tomorrow.

**Comment by AlinaChernenko** [comment]
@wessmith You are right, it should nothing to do with upgrading CocoaPods.  I had the problem with carthage update (it couldn't build the project after fetching) and it was able to build after I installed pods, that's why there are files updates. But they should not be a part of PR.

Just a couple of thoughts...
I guess it gave us some hints how to resolve the issue. It seems that the problems are:
- first of all, carthage complained about impossibility to find the project. So if we change container in scheme for ButtonMerchant target, it resolves the issue but another one appears:
- Project could not be built after fetching during carthage update. So the problems that I found are all related to Target(ButtonMerchant)-> Build Phases dependencies (Manifest and SwiftLint scripts and linked pods binary library) and they all depend on Pods which in my understanding we don't have when carthage is running.  Manifest script and binary linked are updated after pod install, but not SwiftLint. 
- SwiftLint. It can be added as source file to target, for instance or it can be installed as any other frameworks using carthage and custom script.

I am using https://github.com/AlinaChernenko/button-merchant-ios/tree/develop code to install the lib with carthage. It doesn't use SwiftLint. I closed this pulled request as it doesn't keep all interests for UseButton and it contains not really proper updates. So I will be waiting for changes from your side, let me know if there anything I can do to help and make things work.

Thanks, Alina

**Comment by wessmith** [comment]
Hi Alina,

Thanks for bringing this to our attention. Your effort here was really helpful in understanding issue. Please take a look at #9 and see if this resolves the issue for you. If so, we'll get it merged in quickly.

Best,

Wes

**Comment by AlinaChernenko** [comment]
@wessmith it looks good to me, thanks for taking look at it and making updates!

**Pull request closed without merging**
