### PR TITLE
Use AnyObject for protocol definitions

### PR DESCRIPTION
**Pull request by erikkrietsch**
### Issue Link :link:
Addresses #98

### CODE REVIEW

**Comment by danl3v** [comment]
@chrismaddern would you be able to review? This unblocks consumers of your sdk to update to Xcode 12.5

**Comment by chrismaddern** [comment]
Thanks @danl3v 

@wessmith can you take 👀

**Comment by danl3v** [comment]
Thank you for responding @chrismaddern! And thank you for looking @wessmith

**Review by wessmith — COMMENTED** [review]
Thanks @erikkrietsch! This LGTM. Would you mind signing our [CLA](https://docs.google.com/a/usebutton.com/forms/d/e/1FAIpQLSd4U3_aCutkhcHH27INcmvMSamWUOK2CH6p4SAk0ZBuAOgfqA/viewform)?

**Comment by erikkrietsch** [comment]
Done!

**Review by wessmith — APPROVED** [review]

**Pull request merged**
